version: "3"
services:
# database layer for wordpress >> MYSQL Database
  mysql_database:
    image: mysql 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql:/var/lib/mysql
# Wordpress layer depends-on mysql database
  wordpress:
    depends_on:
      - mysql_database
    image: wordpress:latest
    restart: always
    ports:
      - "8005:80"
    environment:
      WORDPRESS_DB_HOST: mysql_database:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: 1234
      WORDPRESS_DB_NAME: wp_db 
    volumes:
      ["./:/var/www/html"] 
  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8002:80
    environment:
      - PMA_HOST:mysql_database
      - PMA_PORT:3306
#Top level volumes 
volumes:
  mysql: {}



